from __future__ import annotations
from pathlib import Path
import discord
from app.version import VERSION

USER_SECTIONS={
'01 • Start Here':'''420VaultBot has four separate search sources: Managed Links (`420_search`), Physical Vault (`420_vault_search`), Google Drive (`420_drive_search`), and Remote Servers (`420_server_search`).\n\nNew/restricted users can use `420_help`, `420_features`, `420_subscribe`, and `420_user_manual`. Complete Terms verification and required paid/license access to unlock protected commands.''',
'02 • Terms & Verification':'''Use the server Terms panel or `420_tos`. Read every Terms page, wait the configured minimum read time, then take the knowledge check. Each attempt samples five questions from the question bank and randomizes answer order. After passing, press **Accept Terms & Verify** so the bot can assign the configured roles and save acceptance for the current Terms version.''',
'03 • Plans & Payments':'''Run `420_subscribe`. Default plans are 1 Month $25, 3 Months $75, 6 Months $100, 1 Year $150, 2 Years $200, 3 Years $250, Lifetime $500. Admins can change these values. Cash App/manual payments require approval; Stripe and PayPal use hosted provider flows when enabled.''',
'04 • Licenses':'''There is no text activation command. A generated license is delivered through Discord UI, normally by DM, with an Activate License button. The configured license channel can also host the persistent activation panel. Do not post license codes publicly. Expired/revoked access returns ordinary users to restricted state.''',
'05 • Feature Stats':'''Open `420_features` to launch the **Feature Center GUI** and see the bot's major features plus current Physical Vault file count/size, Google Drive indexed file count/size, and total unique Link Library count. This is useful for seeing the scale of the server without opening the Admin GUI.''',
'06 • Link Search':'''`420_search <query>` searches the unified Link Library and opens browser-style preview cards. `420_searchkit` is an alias. Results combine bundled legacy lists, managed imports, and scraper-created `links_part_N.txt` parts. Duplicate URLs are normalized/deduplicated. Previous/Next paginate the result set.''',
'07 • Search by Site':'''Open the normal `420_search` browser and press **Search by Site**, or open `420_features` and press **Search by Site** there. Enter the domain and optional keywords in the GUI, then choose **library**, **live**, or **both**. Use **Available Websites** to list domains already present in the Link Library with their indexed-link counts. Domain matching includes subdomains.''',
'08 • Physical Vault':'''`420_vault_search <query>` searches the persistent local/external-drive index. The drive is not rescanned for every search. Results include files, presets, archives, projects, and other indexed production assets. If storage is temporarily offline, metadata can remain indexed while delivery waits for the drive to return.''',
'09 • WAV/MP3 Audition':'''Only `.wav` and `.mp3` are treated as playable audio. Selecting an audio result requests a Discord audio player so you can audition before choosing the original download. Discord controls the Play action and does not allow bots to force autoplay. `.fst` and other preset formats are not audio and remain normal downloadable files.''',
'10 • Google Drive':'''`420_drive_search` opens the configured Google Drive browser. The bot searches synchronized metadata rather than downloading the entire Drive on each query. Delivery depends on Google permissions, indexed availability, file type, and Discord upload limits. Drive-native/open-in-Drive behavior is used when appropriate.''',
'11 • Remote Servers':'''`420_server_search` opens configured remote-server results. In v6.0.1 the implemented remote source is an HTTPS JSON manifest server, optionally using a bearer token. If no server is configured or it is offline, contact an administrator.''',
'12 • Downloads & Limits':'''Original downloads are separate from audio auditioning. Discord delivery obeys the destination server's upload limit. Oversized local items are not silently truncated. Folder/archive operations have safety limits. Admins can disable downloads globally for the guild.''',
'13 • Troubleshooting':'''If a GUI belongs to someone else, run the command yourself. If a panel is stale after an update, rerun its command. Missing Vault files usually mean storage is disconnected or the index needs a scan. Missing Drive results may require a sync. If license DMs fail, enable DMs from server members and ask an admin to resend.''',
'14 • User Commands':'''Core commands stay compact: `420_help`, `420_features`, `420_user_manual`, `420_search`, `420_vault_search`, `420_drive_search`, `420_server_search`, `420_subscribe`, `420_subscription`, `420_status`, `420_version`, plus legacy Vault/sendlink utilities. Live combined Vault, Google Drive, Link Library, audio, and storage totals are available through `420_vault_stats`. Site search is available both through the GUI and `420_search_site <domain> [query]`.''',
'15 • Search Source Map':'''`420_sources` shows all four searchable libraries and the command used for each. This is the quickest way to understand whether a result belongs in managed links, the Physical Vault, Google Drive, or a configured remote server.''',
'16 • Library Statistics':'''`420_features` opens the Feature Center GUI. Its main card shows Physical Vault file count/size/types, Google Drive indexed file count/size, and the deduplicated Link Library total in one place. Use **Refresh Stats** to update it.''',
'17 • Link Search Examples':'''Run `420_search` and use **Search** for a normal query or **Search by Site** for a domain plus optional keywords. The Feature Center GUI also has both entry points. Domain filtering includes subdomains.''',
'18 • Audio vs Original Files':'''Auditioning is for deciding whether a WAV/MP3 is useful before obtaining the original. The original Vault file is not replaced by the preview. Non-audio assets remain downloadable/searchable without pretending they are playable.''',
'19 • Access Troubleshooting':'''If `420_help` only shows a few commands, your account is in restricted mode. Complete the current Terms flow and the required subscription/license activation, or contact an administrator if you were intentionally granted access. Beta Tester policy can bypass payment but not Terms when Terms is enabled.''',
'20 • Full User Command Directory':'''Core: `420_help`, `420_features`, `420_user_manual`, `420_status`, `420_version`. Links: `420_search`/`420_searchkit`, `420_sendlink`; site filtering is also available with `420_search_site`. Vault: `420_vault_search` plus legacy type/size/terms/random/stats/list/download utilities. Cloud/remote: `420_drive_search`, `420_server_search`. Access: `420_tos`, `420_subscribe`, `420_subscription`.'''
}

ADMIN_SECTIONS={
'01 • Operator Start':'''Run `420_setup`, `420_admin`, and `420_diagnostics`. Configure channels, role mappings, Terms, storage sources, subscriptions/payments, licensing, and search behavior. Test the complete flow with a non-admin account before production use.''',
'02 • Admin Dashboard':'''`420_admin` exposes Overview, Vault Storage, Google Drive, Search & Delivery, Link Library & Scraper, Remote File Servers, Channels, Access Roles, Terms & Verification, Licensing, Subscriptions, Payments, Transactions, Security, Logs, Audio Previews, Updates & Recovery, and Diagnostics.''',
'03 • Channels':'''Configure allowed search/delivery channels, the persistent license activation channel, and audit/log destinations. If no search channels are configured, search is allowed everywhere until restricted. `420_showchannels` displays the important mappings.''',
'04 • Roles & Access':'''Map roles by Discord role ID so renames do not break configuration. Recommended roles include TOS Accepted, Verified, Unverified, Paid Member, Beta Tester, plus optional custom bot-admin/Vault Overseer. The bot role must be above roles it assigns/removes and needs Manage Roles.''',
'05 • Terms System':'''Terms are paginated to avoid truncation. The knowledge check samples five randomized questions and randomizes answers. Pass percent and minimum read time are configurable. Acceptance stores a Terms version so material updates can require re-verification. Role assignment must succeed before acceptance is saved.''',
'06 • Physical Vault':'''Configure any accessible local/external/network folder. Scan Changes updates the persistent SQLite/FTS catalog; Full Reindex rebuilds it. A missing/disconnected root must not be treated as permission to erase the index. `420_admin_delete_vault_index` clears only this guild's index and never deletes physical files.''',
'07 • Audio Previews':'''v6.0.1 auditions `.wav` and `.mp3` only. Presets such as `.fst` are never marked playable. Audio audition is separate from original download. Admin audio settings control preview duration/bitrate/cache behavior where transcoding is needed. Discord itself controls playback/autoplay.''',
'08 • Link Library':'''The unified link pipeline discovers `lists.txt`, `lists_part_2.txt`, `lists_part_3.txt`, `lists_part_4.txt`, and future `links_part_5.txt`, `links_part_6.txt`, etc. Imported and scraper links are incrementally indexed in SQLite/FTS. Runtime search combines bundled and managed sources while deduplicating results.''',
'09 • Site Search':'''Users can run the **Search by Site** button inside the Link Search/Feature Center GUI (the underlying query uses `site:domain query`). Matching includes the exact domain and subdomains. This works across bundled runtime lists and managed database links.''',
'10 • Web Scraper':'''Admin → Link Library & Scraper now provides **New Web Scrape**, **Upload TXT**, and **Import Sitemap**. TXT upload accepts one URL per line and saves the normalized/deduplicated result as the next `links_part_N.txt`. Sitemap Import checks an open `/sitemap.xml` or `/sitemap_index.xml`, follows sitemap indexes, extracts HTTP/HTTPS URLs, creates the next link-list part, indexes it, and reloads search. New Web Scrape remains available for crawlable sites.  The crawler has page/concurrency limits, public-host checks, live progress, recent discoveries, Stop, preview/export, and managed-list actions. Successful scraper output can create the next `links_part_N.txt` and reload runtime search without overwriting earlier parts.''',
'11 • Google Drive':'''Configure the root folder/ID and OAuth refresh-token credentials, test access, then synchronize metadata. `420_drive_sync` runs in the background and prevents concurrent guild syncs. Drive search uses indexed metadata. Keep OAuth secrets server-side.''',
'12 • Remote Servers':'''The current implementation uses an HTTPS JSON manifest URL, optional bearer token, and server name. Test/sync before exposing `420_server_search`. Temporary downtime should mark the source unavailable rather than destroy indexed metadata. Do not document arbitrary SFTP/SMB as implemented in this build.''',
'13 • Subscription Plans':'''Defaults: 1 Month $25 / 30d; 3 Months $75 / 90d; 6 Months $100 / 182d; 1 Year $150 / 365d; 2 Years $200 / 730d; 3 Years $250 / 1095d; Lifetime $500. Admin GUI can change plan name, price, duration, grace days, Stripe Price ID, and PayPal Plan ID.''',
'14 • Payments':'''Cash App/manual transactions remain pending until administrator approval. Stripe and PayPal use provider-hosted flows when enabled. Provider webhook IDs/events are deduplicated to reduce duplicate fulfillment. Never store raw PAN/CVV or expose payment secrets.''',
'15 • Licensing':'''Licenses use a private HMAC signing secret plus database state. Generated licenses are assigned to the selected customer and activation UI is delivered by DM when possible. Admin tools support generation/grants, resend, revoke, inspect, list, reset activation, and payment approval. Keep `LICENSE_SIGNING_SECRET` private.''',
'16 • API / Base44':'''`VAULT_API_KEY` is the server-side bearer credential (Base44 may store it as `VAULT_API_SECRET`). It is separate from `LICENSE_SIGNING_SECRET`. API routes also use guild/user identity headers and admin routes re-check current Discord administrative authority. Do not expose secrets client-side.''',
'17 • Watchdog & Heartbeat':'''`run_420vault_watchdog.bat` is a Windows process supervisor: it restarts Python after exit without requiring keyboard input and writes supervisor events to `logs/watchdog.log`. It is not Discord's Gateway heartbeat. discord.py handles Gateway heartbeat inside the running process. The independent health watchdog can report latency/thread state and optionally request Windows to keep the system awake while allowing the display to turn off.''',
'18 • Updates & Recovery':'''Preserve `.env` and persistent database/data when installing a new release. Admin Updates & Recovery accepts a build ZIP or extracted folder through the updater. After installation, press **Restart Bot** in the same panel to shut down cleanly; the packaged watchdog starts the bot again and loads the new code. After Discord reconnects, the bot posts a restart-success confirmation with the running version and measured downtime. Back up the database before schema-changing releases and verify the package version/root before distribution.''',
'19 • Diagnostics':'''`420_diagnostics` reports database health, configured channels, Vault path/index count, loaded links, heartbeat state/interval/latency, and keep-awake state. `420_features` gives a user-facing feature card plus Vault size, Drive size, and total link count.''',
'20 • Admin Commands':'''`420_admin_manual` • `420_setup` • `420_admin` • `420_diagnostics` • `420_vault_path` • `420_reindex_vault` • `420_admin_delete_vault_index` • `420_drive_config` • `420_drive_sync` • `420_drive_status` • `420_importlinks` • `420_reloadlinks` • `420_resolvelinks` • `420_showchannels` • `420_lockdown` • `420_unlock` • `420_exportserver` • license/payment administration commands.''',
'21 • Security Checklist':'''Never ship `.env`, bot tokens, OAuth refresh tokens, payment secrets, API bearer keys, or license-signing secrets. Verify role hierarchy, guild scoping, webhook signatures/idempotency, path traversal protection, upload limits, backup/recovery, and version consistency before release.''',
'22 • Feature/Stats Commands':'''`420_features` opens the combined **Feature Center GUI**. Its cards show Vault, Drive and Link totals, and its buttons open Link Search, Search by Site, Vault, Drive and Remote browsing. These are useful for verifying what the running installation has actually indexed rather than relying on marketing numbers.''',
'23 • Direct Admin Panel Commands':'''v6.0.1 is GUI-first. Run `420_admin` once, then use its section menu for Link Library/Scraper, Audio, Roles, Channels, Terms, Licensing, Subscriptions, Payments, Transactions, Remote Servers, Security, Updates and Diagnostics. Those sections are not duplicated as standalone shortcut commands.''',
'24 • Link Search Operations':'''Use **420_admin → Link Library & Scraper** for managed lists, scraper jobs/imports and link totals. Users use the **Search by Site** GUI button in the normal Link Search or Feature Center.''',
'25 • Vault Operations':'''Use **Admin → Vault Storage** for path, connection test, scan, full reindex and stats. The user Feature Center also shows the current Vault count/size/types. The explicit delete-index maintenance command still requires confirmation and never deletes physical files.''',
'26 • Drive Operations':'''Use **Admin → Google Drive** for folder, OAuth, test, sync, status, archive parsing and disconnect. The Feature Center shows current indexed Drive totals. Metadata-derived byte totals can differ from the provider UI when size metadata is unavailable.''',
'27 • Payment & License Operations':'''Use `420_payments_admin`, `420_transactions_admin`, `420_subscriptions_admin`, and `420_licenses_admin` to jump directly into those dashboard sections. Existing administrative text commands remain available for approval, resend, revoke, inspection, listing and reset workflows.''',
'28 • Roles, Channels & Terms Operations':'''Use `420_roles_admin`, `420_channels_admin`, and `420_tos_admin` to jump directly to their control panels. Keep role hierarchy valid, use role IDs for mappings, and republish/reverify Terms when the configured Terms version materially changes.''',
'29 • Recovery & Security Operations':'''Use `420_updates_admin` for updater/recovery controls and `420_security_admin` for the security overview. Keep `.env` and persistent data out of public release archives. Validate backups before upgrades and never expose bot/payment/OAuth/API/signing secrets in Discord.''',
'30 • Complete Operator Directory':'''Primary operator interface: `420_admin` plus `420_setup`, `420_admin_manual` and `420_diagnostics`. Use the Admin Dashboard section menu for Vault, Drive, Links/Scraper, Roles, Channels, Terms, Licensing, Subscriptions, Payments, Transactions, Remote Servers, Security, Logs, Audio, Updates and Diagnostics. Legacy maintenance/action commands remain where a direct textual operation is useful.'''
}

class ManualSelect(discord.ui.Select):
 def __init__(self,v):
  self.v=v
  opts=[discord.SelectOption(label=k[:100],value=k) for k in v.sections]
  super().__init__(placeholder='Choose a manual chapter…',options=opts,min_values=1,max_values=1)
 async def callback(self,i):self.v.section=self.values[0];await i.response.edit_message(embed=self.v.embed(),view=self.v)

class ManualView(discord.ui.View):
 def __init__(self,owner_id,admin=False):
  super().__init__(timeout=1800);self.owner_id=owner_id;self.admin=admin;self.sections=ADMIN_SECTIONS if admin else USER_SECTIONS;self.section=next(iter(self.sections));self.add_item(ManualSelect(self))
 def embed(self):
  e=discord.Embed(title='🛠️ 420VaultBot Complete Admin Manual' if self.admin else '📘 420VaultBot Complete User Manual',description=self.sections[self.section],color=discord.Color.dark_green())
  keys=list(self.sections);n=keys.index(self.section)+1
  e.add_field(name='Chapter',value=f'**{n}/{len(keys)} — {self.section}**',inline=False)
  e.add_field(name='Navigation',value='Use the chapter menu below. The PDF button sends the full printable manual.',inline=False)
  e.set_footer(text=f'420VaultBot v{VERSION} • Complete built-in manual • {len(keys)} chapters')
  return e
 @discord.ui.button(label='Download Full PDF',emoji='📄',style=discord.ButtonStyle.secondary,row=2)
 async def pdf(self,i,b):
  name='420VaultBot_Admin_Manual_v6.0.1.pdf' if self.admin else '420VaultBot_User_Manual_v6.0.1.pdf'
  p=Path(__file__).resolve().parents[2]/'docs'/name
  if not p.is_file():return await i.response.send_message('The manual PDF is missing from this installation.',ephemeral=True)
  await i.response.send_message(file=discord.File(p,filename=name),ephemeral=True)
 async def interaction_check(self,i):
  if i.user.id!=self.owner_id:await i.response.send_message('Open your own manual with the manual command.',ephemeral=True);return False
  return True
